INSERT INTO BATCH_STEP_EXECUTION_SEQ values(0);

INSERT INTO BATCH_JOB_EXECUTION_SEQ values(0);

INSERT INTO BATCH_JOB_SEQ values(0);


INSERT INTO CUSTOMER_SEQ values(5);

INSERT INTO TRADE_SEQ values(0);

INSERT INTO CUSTOMER_READ (ID, NAME, CREDIT) VALUES(1,'read1','111');
INSERT INTO CUSTOMER_READ (ID, NAME, CREDIT) VALUES(2,'read2','222');
INSERT INTO CUSTOMER_READ (ID, NAME, CREDIT) VALUES(3,'read3','333');
INSERT INTO CUSTOMER_READ (ID, NAME, CREDIT) VALUES(4,'read4','444');

