select
    ALL_TAB_COLS.*
    , ALL_TAB_COMMENTS.COMMENTS as TAB_COMMENT
    , ALL_COL_COMMENTS.COMMENTS as COL_COMMENT
    , ALL_CONSTRAINTS.CONSTRAINT_NAME
    , ALL_CONSTRAINTS.CONSTRAINT_TYPE
    , ALL_CONS_COLUMNS.POSITION
from SYS.ALL_TAB_COLS
left outer join ALL_TAB_COMMENTS on ALL_TAB_COMMENTS.OWNER = ALL_TAB_COLS.OWNER and ALL_TAB_COMMENTS.TABLE_NAME = ALL_TAB_COLS.TABLE_NAME
left outer join ALL_COL_COMMENTS on ALL_COL_COMMENTS.OWNER = ALL_TAB_COLS.OWNER and ALL_COL_COMMENTS.TABLE_NAME = ALL_TAB_COLS.TABLE_NAME and ALL_COL_COMMENTS.COLUMN_NAME = ALL_TAB_COLS.COLUMN_NAME
left outer join ALL_CONSTRAINTS on ALL_CONSTRAINTS.OWNER = ALL_TAB_COLS.OWNER and ALL_CONSTRAINTS.CONSTRAINT_TYPE = 'P' and ALL_CONSTRAINTS.TABLE_NAME = ALL_TAB_COLS.TABLE_NAME
left outer join ALL_CONS_COLUMNS on ALL_CONS_COLUMNS.OWNER = ALL_TAB_COLS.OWNER and ALL_CONS_COLUMNS.CONSTRAINT_NAME = ALL_CONSTRAINTS.CONSTRAINT_NAME and ALL_CONS_COLUMNS.TABLE_NAME = ALL_TAB_COLS.TABLE_NAME and ALL_CONS_COLUMNS.COLUMN_NAME = ALL_TAB_COLS.COLUMN_NAME
where 1 = 1
    and ALL_TAB_COLS.OWNER in (
        ''
        , 'TEST'
    )
order by
    ALL_TAB_COLS.OWNER
    , ALL_TAB_COLS.TABLE_NAME
    , ALL_TAB_COLS.COLUMN_ID
;
