select
    'CREATE SYNONYM ' || ALL_TAB_COMMENTS.TABLE_NAME || ' FOR ' || ALL_TAB_COMMENTS.OWNER || '.' || ALL_TAB_COMMENTS.TABLE_NAME || ';' as CREATE_SYNONYM_01
    , 'CREATE PUBLIC SYNONYM ' || ALL_TAB_COMMENTS.TABLE_NAME || ' FOR ' || ALL_TAB_COMMENTS.OWNER || '.' || ALL_TAB_COMMENTS.TABLE_NAME || ';' as CREATE_PUBLIC_SYNONYM_01
    , ALL_TAB_COMMENTS.*
from SYS.ALL_TAB_COMMENTS /* 테이블코멘트 */
where 1 = 1
    and ALL_TAB_COMMENTS.OWNER in (
        'TEST'
    )
order by
    ALL_TAB_COMMENTS.OWNER, ALL_TAB_COMMENTS.TABLE_NAME
;

