CREATE TABLE COMTNCOMMUTE (
     WRKTM_ID           CHAR(20) NOT NULL,
     EMPLYR_ID          VARCHAR(20) NOT NULL,
     ORGNZT_ID          VARCHAR(20) NULL,
     WRKT_DT            VARCHAR(10) NOT NULL, 
     WRK_START_TIME     VARCHAR(14) NULL, 
     WRK_END_TIME       VARCHAR(14) NULL, 
     WRK_HOURS          CHAR(2) NULL, 
     OVTMWRK_HOURS      CHAR(2) NULL,
     WRK_START_STATUS   VARCHAR(10) NULL, 
     WRK_END_STATUS     VARCHAR(10) NULL, 
     RM                 VARCHAR(100) NULL,
     FRST_REGISTER_ID   VARCHAR(20) NULL,
     FRST_REGIST_PNTTM  DATETIME NULL,
     LAST_UPDUSR_ID     VARCHAR(20) NULL,
     LAST_UPDT_PNTTM    DATETIME NULL,
 PRIMARY KEY (EMPLYR_ID, WRKT_DT)
);