CREATE TABLE COMTECOPSEQ
(
	TABLE_NAME            VARCHAR2(20)  NOT NULL ,
	NEXT_ID               NUMBER(30)  NULL ,
CONSTRAINT  COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME)
);




CREATE TABLE COMTCCMMNCLCODE
(
	CL_CODE               CHAR(3)  NOT NULL ,
	CL_CODE_NM            VARCHAR2(60)  NULL ,
	CL_CODE_DC            VARCHAR2(200)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTCCMMNCLCODE_PK PRIMARY KEY (CL_CODE)
);




CREATE TABLE COMTCCMMNCODE
(
	CODE_ID               VARCHAR2(6)  NOT NULL ,
	CODE_ID_NM            VARCHAR2(60)  NULL ,
	CODE_ID_DC            VARCHAR2(200)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	CL_CODE               CHAR(3)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTCCMMNCODE_PK PRIMARY KEY (CODE_ID),
CONSTRAINT  COMTCCMMNCODE_FK1 FOREIGN KEY (CL_CODE) REFERENCES COMTCCMMNCLCODE(CL_CODE) ON DELETE SET NULL
);

CREATE INDEX COMTCCMMNCODE_i01 ON COMTCCMMNCODE
(CL_CODE  ASC);



CREATE TABLE COMTCCMMNDETAILCODE
(
	CODE_ID               VARCHAR2(6)  NOT NULL ,
	CODE                  VARCHAR2(15)  NOT NULL ,
	CODE_NM               VARCHAR2(60)  NULL ,
	CODE_DC               VARCHAR2(200)  NULL ,
	USE_AT                CHAR(1)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
CONSTRAINT  COMTCCMMNDETAILCODE_PK PRIMARY KEY (CODE_ID,CODE),
CONSTRAINT  COMTCCMMNDETAILCODE_FK1 FOREIGN KEY (CODE_ID) REFERENCES COMTCCMMNCODE(CODE_ID)
);

CREATE INDEX COMTCCMMNDETAILCODE_i01 ON COMTCCMMNDETAILCODE
(CODE_ID  ASC);



CREATE TABLE COMTNAUTHORGROUPINFO
(
	GROUP_ID              CHAR(20)  NOT NULL ,
	GROUP_NM              VARCHAR2(60)  NOT NULL ,
	GROUP_CREAT_DE        CHAR(20)  NOT NULL ,
	GROUP_DC              VARCHAR2(100)  NULL ,
CONSTRAINT  COMTNAUTHORGROUPINFO_PK PRIMARY KEY (GROUP_ID)
);




CREATE TABLE COMTNORGNZTINFO
(
	ORGNZT_ID             CHAR(20)  NOT NULL ,
	ORGNZT_NM             VARCHAR2(20)  NOT NULL ,
	ORGNZT_DC             VARCHAR2(100)  NULL ,
CONSTRAINT  COMTNORGNZTINFO_PK PRIMARY KEY (ORGNZT_ID)
);




CREATE TABLE COMTNFILE
(
	ATCH_FILE_ID          CHAR(20)  NOT NULL ,
	CREAT_DT              DATE  NOT NULL ,
	USE_AT                CHAR(1)  NULL ,
CONSTRAINT  COMTNFILE_PK PRIMARY KEY (ATCH_FILE_ID)
);




CREATE TABLE COMTNFILEDETAIL
(
	ATCH_FILE_ID          CHAR(20)  NOT NULL ,
	FILE_SN               NUMBER(10)  NOT NULL ,
	FILE_STRE_COURS       VARCHAR2(2000)  NOT NULL ,
	STRE_FILE_NM          VARCHAR2(255)  NOT NULL ,
	ORIGNL_FILE_NM        VARCHAR2(255)  NULL ,
	FILE_EXTSN            VARCHAR2(20)  NOT NULL ,
	FILE_CN               CLOB  NULL ,
	FILE_SIZE             NUMBER(8)  NULL ,
CONSTRAINT  COMTNFILEDETAIL_PK PRIMARY KEY (ATCH_FILE_ID,FILE_SN),
CONSTRAINT  COMTNFILEDETAIL_FK1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES COMTNFILE(ATCH_FILE_ID)
);

CREATE INDEX COMTNFILEDETAIL_i01 ON COMTNFILEDETAIL
(ATCH_FILE_ID  ASC);



CREATE TABLE COMTNINSTTCODE
(
	INSTT_CODE            CHAR(7)  NOT NULL ,
	ALL_INSTT_NM          VARCHAR2(255)  NULL ,
	LOWEST_INSTT_NM       VARCHAR2(100)  NULL ,
	INSTT_ABRV_NM         VARCHAR2(50)  NULL ,
	ODR                   CHAR(1)  NULL ,
	ORD                   CHAR(3)  NULL ,
	INSTT_ODR             CHAR(2)  NULL ,
	UPPER_INSTT_CODE      CHAR(7)  NULL ,
	BEST_INSTT_CODE       CHAR(7)  NULL ,
	REPRSNT_INSTT_CODE    CHAR(7)  NULL ,
	INSTT_TY_LCLAS        CHAR(2)  NULL ,
	INSTT_TY_MLSFC        CHAR(2)  NULL ,
	INSTT_TY_SCLAS        CHAR(2)  NULL ,
	TELNO                 VARCHAR2(20)  NULL ,
	FXNUM                 VARCHAR2(20)  NULL ,
	CREAT_DE              CHAR(20)  NULL ,
	ABL_DE                CHAR(20)  NULL ,
	ABL_ENNC              CHAR(1)  NULL ,
	CHANGE_DE             CHAR(20)  NULL ,
	CHANGE_TIME           VARCHAR2(6)  NULL ,
	BSIS_DE               CHAR(20)  NULL ,
	SORT_ORDR             NUMBER(8)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  COMTNINSTTCODE_PK PRIMARY KEY (INSTT_CODE)
);




CREATE TABLE COMTNINSTTCODERECPTNLOG
(
	OCCRRNC_DE            CHAR(20)  NOT NULL ,
	INSTT_CODE            CHAR(7)  NOT NULL ,
	OPERT_SN              NUMBER(10)  NOT NULL ,
	CHANGE_SE_CODE        VARCHAR2(2)  NULL ,
	PROCESS_SE            VARCHAR2(2)  NULL ,
	ETC_CODE              CHAR(2)  NULL ,
	ALL_INSTT_NM          VARCHAR2(255)  NULL ,
	LOWEST_INSTT_NM       VARCHAR2(100)  NULL ,
	INSTT_ABRV_NM         VARCHAR2(50)  NULL ,
	ODR                   CHAR(1)  NULL ,
	ORD                   CHAR(3)  NULL ,
	INSTT_ODR             CHAR(2)  NULL ,
	UPPER_INSTT_CODE      CHAR(7)  NULL ,
	BEST_INSTT_CODE       CHAR(7)  NULL ,
	REPRSNT_INSTT_CODE    CHAR(7)  NULL ,
	INSTT_TY_LCLAS        CHAR(2)  NULL ,
	INSTT_TY_MLSFC        CHAR(2)  NULL ,
	INSTT_TY_SCLAS        CHAR(2)  NULL ,
	TELNO                 VARCHAR2(20)  NULL ,
	FXNUM                 VARCHAR2(20)  NULL ,
	CREAT_DE              CHAR(20)  NULL ,
	ABL_DE                CHAR(20)  NULL ,
	ABL_ENNC              CHAR(1)  NULL ,
	CHANGE_DE             CHAR(20)  NULL ,
	CHANGE_TIME           VARCHAR2(6)  NULL ,
	BSIS_DE               CHAR(20)  NULL ,
	SORT_ORDR             NUMBER(8)  NULL ,
	FRST_REGISTER_ID      VARCHAR2(20)  NULL ,
	FRST_REGIST_PNTTM     DATE  NULL ,
	LAST_UPDUSR_ID        VARCHAR2(20)  NULL ,
	LAST_UPDT_PNTTM       DATE  NULL ,
CONSTRAINT  COMTNINSTTCODERECPTNLOG_PK PRIMARY KEY (OCCRRNC_DE,INSTT_CODE,OPERT_SN)
);




