select
    rownum
    , OWNER
    , TABLE_NAME
    , COLUMN_NAME
    , DATA_TYPE
    , DATA_TYPE_MOD
    , DATA_TYPE_OWNER
    , DATA_LENGTH
    , DATA_PRECISION
    , DATA_SCALE
    , NULLABLE
    , COLUMN_ID
    , DEFAULT_LENGTH
    , DATA_DEFAULT
    , NUM_DISTINCT
    , LOW_VALUE
    , HIGH_VALUE
    , DENSITY
    , NUM_NULLS
    , NUM_BUCKETS
    , LAST_ANALYZED
    , SAMPLE_SIZE
    , CHARACTER_SET_NAME
    , CHAR_COL_DECL_LENGTH
    , GLOBAL_STATS
    , USER_STATS
    , AVG_COL_LEN
    , CHAR_LENGTH
    , CHAR_USED
    , V80_FMT_IMAGE
    , DATA_UPGRADED
    , HIDDEN_COLUMN
    , VIRTUAL_COLUMN
    , SEGMENT_COLUMN_ID
    , INTERNAL_COLUMN_ID
    , HISTOGRAM
    , QUALIFIED_COL_NAME
from SYS.ALL_TAB_COLS /* 테이블컬럼 */
where 1 = 1
--    and ALL_TAB_COLS.OWNER in (
--        'TEST'
--        , 'TEST2'
--    )
    and ALL_TAB_COLS.OWNER = 'SYS'
    and ALL_TAB_COLS.TABLE_NAME = 'ALL_TAB_COLS'
order by
--    ALL_TAB_COLS.OWNER, ALL_TAB_COLS.TABLE_NAME, ALL_TAB_COLS.COLUMN_ID
    ALL_TAB_COLS.COLUMN_ID
;

