INSERT INTO CUSTOMER_READ (ID, NAME, CREDIT) VALUES(1,'read1','111');
INSERT INTO CUSTOMER_READ (ID, NAME, CREDIT) VALUES(2,'read2','222');
INSERT INTO CUSTOMER_READ (ID, NAME, CREDIT) VALUES(3,'read3','333');
INSERT INTO CUSTOMER_READ (ID, NAME, CREDIT) VALUES(4,'read4','444');

