<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>

<meta name="viewport"
	content="width=device-width, initial-scale=1, shrink-to-fit=no">

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>

<link rel="stylesheet"
	href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
	integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
	crossorigin="anonymous">

<style type="text/css">
.col {
	/* 	background-color: red; */
	border: 1px solid black;
}
</style>

</head>
<body>

	<c:if test="false">
		<!-- <div style="background-image: url('ed_ro102-0.jpg'); width: 2479px; height: 3508px;"></div> -->
		<!-- <div style="background-image: url('ed_ro102-1.jpg'); width: 2479px; height: 3508px;"></div> -->

		<!-- <div style="background-image: url('ed_ro102-0.jpg'); width: 100%; height: 3508px;"></div> -->
		<!-- <div style="background-image: url('ed_ro102-1.jpg'); width: 100%; height: 3508px;"></div> -->

		<a href="#page1"
			onclick="//$('.page').hide();$('#page1').show();$(this).preventDefault();">1페이지</a>
		<a href="#page2"
			onclick="//$('.page').hide();$('#page2').show();$(this).preventDefault();">2페이지</a>

		<div id="page1" name="page1" class="page"
			style="background-image: url('ed_ro102-0.jpg'); width: 100%; height: 3508px; background-size: contain; background-repeat-y: no-repeat;"></div>
		<div id="page2" name="page2" class="page"
			style="background-image: url('ed_ro102-1.jpg'); width: 100%; height: 3508px; background-size: contain; background-repeat-y: no-repeat;"></div>
		<!-- display: none; -->

		<!-- <img src="ed_ro102-0.jpg"> -->

		<div
			style="background-color: red; width: 750px; height: 350px; position: absolute; top: 370px; left: 200px;">
			<!-- <textarea rows="10" cols="10"></textarea> -->
		</div>
	</c:if>

	<c:if test="false">
		<div class="container"
			style="background-image: url('ed_ro102-0.jpg'); width: 100%; height: 3508px; background-size: contain; background-repeat-y: no-repeat;">
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
			<div class="row">
				<div class="col text-right">
					&nbsp;<input type="checkbox">
				</div>
			</div>
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
			<div class="row align-items-end">
				<div class="col-1">&nbsp;</div>
				<div class="col-6">
					<textarea style="resize: none;"></textarea>
				</div>
				<div class="col" style="vertical-align: bottom;">
					<input class="">
				</div>
			</div>
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
			<div class="row">
				<div class="col">&nbsp;</div>
			</div>
		</div>
	</c:if>

	<c:if test="false">
		<!-- Image Map Generated by http://www.image-map.net/ -->
		<img src="ed_ro102-0.jpg" usemap="#image-map"
			style="width: 100%; height: 100%;">

		<map name="image-map">
			<area target="_blank" alt="1" title="1" href="1"
				coords="1249,366,240,937" shape="rect">
			<area target="_blank" alt="2" title="2" href="2"
				coords="1530,843,2305,963" shape="rect">
			<area target="_blank" alt="3" title="3" href="3"
				coords="240,1016,1271,1097" shape="rect">
		</map>
	</c:if>

	<div
		style="background-image: url('ed_ro102-0.jpg'); width: 100%; height: 3508px; background-size: contain; background-repeat-y: no-repeat;">
		<div style="background-color: red; margin-top: 30%;">To:</div>
	</div>

	<!-- <img src="ed_ro102-0.jpg" style="width: 100%; height: 100%;"> -->

	<script type="text/javascript"
		src="${pageContext.request.contextPath}/js/egovframework/com/cmm/jquery-1.4.2.min.js"></script>
	<%-- <script type="text/javascript" src="${pageContext.request.contextPath}/js/egovframework/com/cmm/jquery.js"></script> --%>

	<!-- 	<script type="text/javascript" src="jquery.rwdImageMaps.js"></script> -->
	<script type="text/javascript" src="jquery.rwdImageMaps.min.js"></script>

	<script type="text/javascript">
	$(document).ready(function(e) {
// 	    $('img[usemap]').rwdImageMaps();
	});
	</script>

</body>
</html>